backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img/upload
public_folder: /img/upload
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "text"}
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: "Featured Image", name: "featureImage", widget: "image"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Profile"
        name: "profile"
        widget: "object"
        summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Public", name: "public", widget: "boolean", default: true}
          - {label: "Name", name: "name", widget: "string"}
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Street Address", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Postal Code", name: "post-code", widget: "string"}